@startuml
'https://plantuml.com/sequence-diagram

autonumber

box "PX4 & dop_sim" #LightGreen
entity quadrotor
end box

box "TX2 NX -> ndp_nmpc_qd" #LightBLUE
participant controller
end box
'note right of pt_publisher #aqua
'需要从ROS里拿一个parameter
'确定是选SE3还是NMPC
'end note

box "PC -> cmd_pc" #White
participant planner
entity rviz
end box

note left of planner #aqua
启动就不关了
end note

note left of planner
考虑用FMS库transitions编写状态机;
参考ROS2的写法，使用class的形式组织程序。
end note

note left planner
状态: PLANNING
end note
planner -> planner: 读取路径点，\n 或读取rviz指令，\n 或path planning
planner -> rviz: 绘制Path
'path_planner -> traj_generator: self_defined.srv.FollowPath

planner -> planner: 规划轨迹
planner -> rviz: 绘制traj, 也是Path消息类型

note left of planner
状态: EXECUTION
end note

planner -> controller: action.send_goal, \n设置轨迹参数，重置轨迹开始时间


controller -> controller: 生成控制目标 & 异步执行NMPC控制律
controller -> quadrotor: pub角速度控制指令
controller -> planner: action.publish_feedback, \n告知轨迹跟踪的进度与误差
controller -> rviz: 绘制tf2/Odom，表示当前位置


controller -> planner: action.set_succeeded, \n告知Traj飞行成功
'planner -> planner: self_defined.srv.FollowPath, \n告知Path是否飞行成功

note left of planner
状态: PLANNING
end note

' 状态： TAKEOFF, PLANNING, EXECUTION, LAND


@enduml
